### ISSUE TITLE
Migrate to partial node classification tasks

### ISSUE THREAD

**Issue by ChengFu0118** [vijaydwivedi75/gnn-lspe#2]
Dear Author,

Thanks so much for the code! 

I don't know if LSPE can be used for sub-graph node classification (prediction on part of the nodes). I checked another repo you wrote [(https://github.com/graphdeeplearning/benchmarking-gnns)](url) and it seems I have to generate the features of all the nodes/edges first.

**Comment by vijaydwivedi75** [comment]
Hi @ChengFu0118,
Yes, it can be used for sub-graph node classification, in a similar way as its done with any GNN for, eg, node classification in Cora dataset. If you have a task with missing node/edge features, that may be a different issue to tackle, i guess.
